#!/bin/bash

# https://github.com/dubniczky/Shell-Utilities
# Build the local Dockerfile and quick run it with customizable parameters


DEFAULT_NAME="tempimage:latest"
DEFAULT_PORT="8000:8000"

# Check for help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Build the local Dockerfile and quick run it with customizable parameters"
    echo ""
    echo "Usage: embark [container_name?] [ports?] [args...]"
    echo "   container_name: The name and tag of the image to build. Default: $DEFAULT_NAME"
    echo "   ports: The source and destination ports to expose. Default: $DEFAULT_PORT"
    echo "   args: All subsequent parameters will be passed to the docker run command."
    echo ""
    echo "Examples:"
    echo "   embark - build and run dockerfile with default name and port"
    echo "   embark myimage:latest 80:80 - build and run dockerfile with custom name"
    echo "   embark myimage:latest 80:80 -d - build and run dockerfile with custom name and daemon mode"
    exit 0
fi

# Assign parameters
if [ ! -z $1 ]; then
    DEFAULT_NAME=$1
fi

if [ ! -z $2 ]; then
    DEFAULT_PORT=$2
fi

echo "Container name: $DEFAULT_NAME"
echo "Container port: $DEFAULT_PORT"

# Build the container
if [ -f "Dockerfile" ]; then
    docker build -t $DEFAULT_NAME .
else
    echo "No Dockerfile found in current directory."
    exit 1
fi

# Run the container
docker run -p $DEFAULT_PORT --rm "${@:3}" $DEFAULT_NAME
