#!/bin/bash

# https://github.com/dubniczky/Shell-Utilities
# Clean up common temporary files and folders in the current directory

ITEMS=(
# General
logs
*.log
out
.temp
*.cache
dist
build
*.tmp
*.tmp.*
*.~*
coverage
.coverage
*.sqlite*

# Nodejs
node_modules
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
.grunt
bower_components
jspm_packages
*.tsbuildinfo
.npm
.eslintcache
*.tgz
.yarn-integrity
.next
.nuxt
*.sass-cache
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Python
__pycache__
.pytest_cache
.venv
.Python
*.py[cod]
*.egg-info
*.egg
*.ipynb_checkpoints
develop-eggs
eggs
MANIFEST
*.manifest
pip-log.txt
pip-delete-this-directory.txt
.pybuilder
ipython_config.py
__pypackages__
*.sage.py
.pyre
.pytype

# C/C++/C#
[Bb]uild
[Dd]ebug
obj
bin
lib
lib64
*.out
*.o
*.so
*.i
*.ii

packages
vendor

# OS Specific
.DS_Store
)

# Remove items
REMOVED_ITEMS=$(rm -rfv ${ITEMS[@]} 2> /dev/null)
#echo $REMOVED_ITEMS

# Count removed items
REMOVED_COUNT="0"
if [ ! -z "$REMOVED_ITEMS" ]; then
    REMOVED_COUNT=$(echo "$REMOVED_ITEMS" | wc -l | xargs echo)
fi

# Print summary
echo "Removed $REMOVED_COUNT items."
