#!/bin/bash

# https://github.com/dubniczky/Shell-Utilities
# Activate given python version as the python command


# Check for help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Activate given python version as the python command, or show currently active version"
    echo "Usage: snek [version?]"
    echo "   version: The major and minor version numbers of python to activate"
    echo "Examples:"
    echo "   snek - show current version"
    echo "   snek 3.10 - switch to 3.10 if installed"
    exit 0
fi

# Check for display or update mode
if [ "$#" -ne 1 ]; then
    echo "$(python -V  | sed -e "s/^Python //")"
    exit 0
fi

# Locate binary
BIN_LOC="$(command -v python$1)"
if [ -z $BIN_LOC ]; then
    echo "python$1 binary not found."
    exit 1
fi

# Overwrite soft link
ln -sf $BIN_LOC /usr/local/bin/python
