#!/bin/bash

# https://github.com/dubniczky/Shell-Utilities
# Initialize a python virtual environment and install packages

VENV_NAME=".venv"
VENV_DEPS="requirements.txt"

# Check python installation and create venv
echo "Creating virtual environment... ($VENV_NAME/)"
if python --version > /dev/null; then # python
    python -m venv "$VENV_NAME"
elif python3 --version > /dev/null; then # python3
    python3 -m venv "$VENV_NAME"
elif py --version > /dev/null; then # py
    py -m venv "$VENV_NAME"
else
    echo "Error: Could not find python runtime."
    return 1
fi

# Install packages with pip
echo "Installing packages... (/$VENV_DEPS)"
if [ -f "$VENV_DEPS" ]; then
    echo "Installing dependencies from requirements file..."
    ./$VENV_NAME/bin/pip install -r $VENV_DEPS
else
    echo "No requirements file found, skipping install."
    echo "Created requirements file: $VENV_DEPS"
fi

# Show instructions
echo "Environment loaded!"
echo ""
echo "Activate:"
echo ". $VENV_NAME/bin/activate"
